apiVersion: v2
name: fennel-node
description: A Helm chart for deploying Fennel Substrate nodes following official Parity patterns
type: application
version: 0.3.0
appVersion: "0.2.0"
home: "https://github.com/corruptedaesthetic/fennel-solonet"
sources:
  - "https://github.com/corruptedaesthetic/fennel-solonet"
maintainers:
  - name: corruptedaesthetic
    email: ""
keywords:
  - blockchain
  - substrate
  - polkadot
  - validator
  - solochain
  - fennel

# Keywords for discoverability
keywords:
  - blockchain
  - substrate
  - polkadot
  - validator
  - solochain
  - fennel

# Dependencies - using Parity's node chart
dependencies:
  - name: node                  # must match the 'name:' in Parity's Chart.yaml
    version: "5.15.0"           # Latest Parity chart version
    repository: "https://paritytech.github.io/helm-charts"
    condition: node.enabled


