# Staging-specific overrides
image:
  repository: "ghcr.io/corruptedaesthetic/fennel-solonet"
  tag: "staging-placeholder"  # Will be patched by CI with actual SHA

# Use the staging chain spec key
chainspec:
  file: "staging.json"

# Parity node chart overrides for staging
node:
  # Override image for staging
  image:
    repository: "ghcr.io/corruptedaesthetic/fennel-solonet"
    tag: "staging-placeholder"
    pullPolicy: Always

  # Node configuration for staging
  node:
    # Required: specify the chain name
    chain: "fennel"  # Adding the required chain field
    
    # Use staging chainspec
    customChainspecPath: "/chainspec/staging.json"
    
    # Persistent storage with local-path for staging
    chainData:
      storageClass: "local-path"  # Updated for staging environment
      volumeSize: "100Gi"
      # Enable snapshot for faster sync (if available)
      # kubernetesVolumeSnapshot: "fennel-staging-snapshot"
      pruning: 1000  # Keep last 1000 blocks for staging

    # Keystore configuration
    chainKeystore:
      storageClass: "local-path"
      volumeSize: "10Mi"
      mountInMemory:
        enabled: false  # Use persistent storage for staging

    # P2P and RPC settings
    perNodeServices:
      apiService:
        enabled: true
        type: ClusterIP
      p2pService:
        enabled: true
        type: NodePort
        nodePort: 30333

  # Resources for staging (moderate)
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

  # Service monitor for Prometheus
  serviceMonitor:
    enabled: true
    interval: "30s"

  # Additional environment variables for staging
  extraEnvVars:
    - name: RUST_LOG
      value: "info"
    - name: ENVIRONMENT
      value: "staging"
