# Base image settings (overwritten in CI)
image:
  repository: "ghcr.io/corruptedaesthetic/fennel-solonet"
  tag:        "dev-placeholder"

# Which key in the ConfigMap to use for genesis config
chainspec:
  file: "development.json"

# ConfigMap name holding the chain spec (overwritten in CI)
# Production-grade defaults (can all be overridden in env-specific files)
node:
  chainSpecConfigMap: "fennel-chainspec"
  enabled: true  # Enable the Parity node subchart
  
  chainData:
    volumeSize: "100Gi"         # size of the PVC for chain data
    storageClass: "fast-ssd"    # StorageClass for performance
    database: "rocksdb"         # or "paritydb"
    pruning: 1000               # number of state changes to retain

  chainSnapshot:
    enabled: false              # turn on via env override
    method: ""                  # populated in values-*.yaml if needed
    url: ""                     # populated in values-*.yaml if needed

  existingSecrets:
    keys: []                    # list of K8s Secret names for validator keys
    nodeKey: {}                 # secretName: <your-node-key-secret>

  perNodeServices: {}           # See staging overrides for examples

  serviceMonitor:
    enabled: false              # turn on via env override
    interval: ""                # e.g. "30s"

resources: {}                   # Pod CPU/memory requests & limits
